const API_URL='https://script.google.com/macros/s/AKfycbxZfud-3L6xaQdPv4TqbimUxLOHMHDRgN6l85bng5b5SzWaqmeEWK1zWc1F8qxGQZW0/exec';let token=localStorage.getItem('finance_token'),data={};const $=id=>document.getElementById(id);
async function api(action,x={}){const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...x})});return r.json()}
function showLogin(){$('login').classList.remove('hidden');$('forgot').classList.add('hidden')}function showForgot(){$('login').classList.add('hidden');$('forgot').classList.remove('hidden')}
async function login(){const r=await api('login',{userId:$('loginUser').value,password:$('loginPass').value});if(!r.ok){$('loginMsg').textContent=r.error;return}token=r.token;localStorage.setItem('finance_token',token);load()}
async function load(){const r=await api('getApp',{token});if(!r.ok){localStorage.removeItem('finance_token');token=null;showLogin();return}data=r;$('login').classList.add('hidden');$('forgot').classList.add('hidden');$('app').classList.remove('hidden');render()}
async function logout(){await api('logout',{token});localStorage.removeItem('finance_token');location.reload()}
async function forgot(){const r=await api('forgotPassword',{email:$('forgotEmail').value});$('forgotMsg').textContent=r.ok?r.message:r.error}
function render(){const s=data.settings||{},p=data.reports||{};$('companyTitle').textContent=s.companyName||'Finance Manager';$('companySsm').textContent=s.ssmNumber?'SSM: '+s.ssmNumber:'';$('companyName').value=s.companyName||'';$('ssmNumber').value=s.ssmNumber||'';$('recoveryEmail').value=s.recoveryEmail||'';$('financialYearStart').value=s.financialYearStart||'';$('income').textContent=money(p.income);$('expenses').textContent=money(p.expense);$('profit').textContent=money(p.profit);$('assets').textContent=money(p.assets);$('recent').innerHTML=(data.transactions||[]).slice(-8).reverse().map(t=>`<p>${fmtDate(t.date)} — <b>${esc(t.type)}</b> — ${esc(t.description)} — ${money(t.amount)}</p>`).join('')||'<p>Tiada transaksi.</p>';populateAccountFields();renderTx();renderAccounts();renderReports()}
function renderTx(){$('txBody').innerHTML=(data.transactions||[]).slice().reverse().map(t=>`<tr><td>${fmtDate(t.date)}</td><td>${esc(t.type)}</td><td>${esc(t.category)}</td><td>${esc(t.description)}</td><td>${money(t.amount)}</td><td>${t.receiptUrl?`<a href="${t.receiptUrl}" target="_blank">View</a>`:''}</td><td><button onclick="delTx('${t.id}')">Delete</button></td></tr>`).join('')}
function renderAccounts(){$('acBody').innerHTML=(data.accounts||[]).map(a=>`<tr><td>${a.code}</td><td>${esc(a.name)}</td><td>${esc(a.type)}</td><td>${esc(a.status)}</td></tr>`).join('')}
function renderReports(){const p=data.reports||{},l=p.ledger||[];$('reportsBox').innerHTML=`<div class="report-grid"><div class="report"><h3>Profit & Loss</h3><p>Income: <b>${money(p.income)}</b></p><p>Expenses: <b>${money(p.expense)}</b></p><p>Net Profit: <b>${money(p.profit)}</b></p></div><div class="report"><h3>Balance Sheet</h3><p>Assets: <b>${money(p.assets)}</b></p><p>Liabilities: <b>${money(p.liabilities)}</b></p><p>Equity + Profit: <b>${money(p.equityPlusProfit)}</b></p><p>Check: <b>${Math.abs(p.assets-(p.liabilities+p.equityPlusProfit))<0.01?'BALANCED':'CHECK JOURNALS'}</b></p></div></div><div class="report"><h3>Trial Balance</h3><table><tr><th>Code</th><th>Account</th><th>Debit</th><th>Credit</th></tr>${l.map(a=>{const d=Number(a.debit||0),c=Number(a.credit||0),net=d-c;return `<tr><td>${a.code}</td><td>${esc(a.name)}</td><td>${money(net>0?net:0)}</td><td>${money(net<0?-net:0)}</td></tr>`}).join('')}<tr><th colspan="2">Total</th><th>${money(l.reduce((s,a)=>s+Math.max(Number(a.debit||0)-Number(a.credit||0),0),0))}</th><th>${money(l.reduce((s,a)=>s+Math.max(Number(a.credit||0)-Number(a.debit||0),0),0))}</th></tr></table></div><div class="report"><h3>General Ledger</h3><table><tr><th>Date</th><th>Account</th><th>Debit</th><th>Credit</th><th>Description</th></tr>${(data.journals||[]).slice().reverse().map(j=>`<tr><td>${fmtDate(j.date)}</td><td>${j.code} ${esc(j.name)}</td><td>${money(j.debit)}</td><td>${money(j.credit)}</td><td>${esc(j.description)}</td></tr>`).join('')}</table></div><div class="report"><h3>Monthly Income / Expenses</h3>${Object.entries(p.monthly||{}).sort().map(([m,v])=>`<p>${m}: Income ${money(v.income)} | Expenses ${money(v.expense)} | Profit ${money(v.income-v.expense)}</p>`).join('')||'<p>Tiada data.</p>'}</div>`}
async function saveTx(){const f=$('receipt').files[0];let receipt=null;if(f){if(f.size>5*1024*1024){alert('Receipt maksimum 5MB.');return}receipt={name:f.name,mimeType:f.type,data:await b64(f)}}const type=$('type').value;const payload={token,type,date:$('date').value,description:$('description').value,amount:$('amount').value,receipt};if(type==='Transfer'){payload.fromAccount=$('fromAccount').value;payload.toAccount=$('toAccount').value}else{payload.category=$('category').value;payload.account=$('account').value}const r=await api('saveTransaction',payload);if(!r.ok){alert(r.error);return}['category','description','amount','account','fromAccount','toAccount'].forEach(x=>$(x).value='');$('receipt').value='';await load()}
async function delTx(id){if(!confirm('Delete transaksi ini?'))return;const r=await api('deleteTransaction',{token,id});if(!r.ok)alert(r.error);else await load()}
async function saveSettings(){const r=await api('saveSettings',{token,companyName:$('companyName').value,ssmNumber:$('ssmNumber').value,recoveryEmail:$('recoveryEmail').value,financialYearStart:$('financialYearStart').value});$('settingsMsg').textContent=r.ok?'Settings disimpan.':r.error;if(r.ok)await load()}
async function changePassword(){const r=await api('changePassword',{token,currentPassword:$('currentPassword').value,newPassword:$('newPassword').value});$('settingsMsg').textContent=r.ok?'Password berjaya ditukar.':r.error;if(r.ok){$('currentPassword').value='';$('newPassword').value=''}}
async function saveAccount(){const r=await api('saveAccount',{token,code:$('acCode').value,name:$('acName').value,type:$('acType').value});if(!r.ok)alert(r.error);else await load()}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function toggleTransferFields(){const isTransfer=$('type').value==='Transfer';$('transferFields').classList.toggle('hidden',!isTransfer);$('normalFields').classList.toggle('hidden',isTransfer);if(!isTransfer)populateNormalFields();}
function populateAccountFields(){if(!$('type'))return;populateTransferFields();populateNormalFields();}
function populateTransferFields(){const opts=(data.accounts||[]).filter(a=>a.type==='Asset'&&a.status==='Active').map(a=>`<option value="${a.code}">${a.code} ${esc(a.name)}</option>`).join('');const f=$('fromAccount'),t=$('toAccount');if(f){const old=f.value;f.innerHTML='<option value="">From Account</option>'+opts;f.value=old||''}if(t){const old=t.value;t.innerHTML='<option value="">To Account</option>'+opts;t.value=old||''}}
function populateNormalFields(){const type=$('type').value;const cat=$('category'),acc=$('account');if(!cat||!acc)return;let cats=[],accounts=[];if(type==='Income'){cats=(data.accounts||[]).filter(a=>a.type==='Income'&&a.status==='Active');accounts=(data.accounts||[]).filter(a=>a.type==='Asset'&&a.status==='Active')}else if(type==='Expense'){cats=(data.accounts||[]).filter(a=>a.type==='Expense'&&a.status==='Active');accounts=(data.accounts||[]).filter(a=>a.type==='Asset'&&a.status==='Active')}else if(type==='Asset'){cats=(data.accounts||[]).filter(a=>a.type==='Asset'&&a.status==='Active'&&a.code!=='1000'&&a.code!=='1010');accounts=(data.accounts||[]).filter(a=>a.type==='Asset'&&a.status==='Active')}else if(type==='Liability'){cats=(data.accounts||[]).filter(a=>a.type==='Liability'&&a.status==='Active');accounts=(data.accounts||[]).filter(a=>a.type==='Asset'&&a.status==='Active')}else if(type==='Equity'){cats=(data.accounts||[]).filter(a=>a.type==='Equity'&&a.status==='Active');accounts=(data.accounts||[]).filter(a=>a.type==='Asset'&&a.status==='Active')}else{cats=data.accounts||[];accounts=data.accounts||[]}const oldCat=cat.value,oldAcc=acc.value;cat.innerHTML='<option value="">Select Main Account</option>'+cats.map(a=>`<option value="${a.code}">${a.code} ${esc(a.name)}</option>`).join('');acc.innerHTML='<option value="">Select Cash/Bank Account</option>'+accounts.map(a=>`<option value="${a.code}">${a.code} ${esc(a.name)}</option>`).join('');if(cats.some(a=>a.code===oldCat))cat.value=oldCat;if(accounts.some(a=>a.code===oldAcc))acc.value=oldAcc;const l1=$('categoryLabel'),l2=$('accountLabel');if(type==='Asset'){l1.textContent='Asset Account';l2.textContent='Paid From'}else if(type==='Liability'){l1.textContent='Liability Account';l2.textContent='Received Into'}else if(type==='Equity'){l1.textContent='Equity Account';l2.textContent='Cash/Bank Account'}else{l1.textContent='Category / Main Account';l2.textContent='Account / Cash-Bank'}}
function fmtDate(v){if(!v)return '';const d=new Date(v);if(isNaN(d.getTime()))return String(v);return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()}
function money(n){return 'RM '+Number(n||0).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2})}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function b64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result.split(',')[1]);r.onerror=rej;r.readAsDataURL(f)})}
$('date').value=new Date().toISOString().slice(0,10);toggleTransferFields();if(token)load()
