const API_URL='https://script.google.com/macros/s/AKfycbxZfud-3L6xaQdPv4TqbimUxLOHMHDRgN6l85bng5b5SzWaqmeEWK1zWc1F8qxGQZW0/exec';let token=localStorage.getItem('finance_token');let appData={};
const $=id=>document.getElementById(id);
async function api(action,data={}){const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...data})});return r.json()}
function showLogin(){$('login').classList.remove('hidden');$('forgot').classList.add('hidden')}
function showForgot(){$('login').classList.add('hidden');$('forgot').classList.remove('hidden')}
async function login(){const r=await api('login',{userId:$('loginUser').value,password:$('loginPass').value});if(!r.ok){$('loginMsg').textContent=r.error;return}token=r.token;localStorage.setItem('finance_token',token);await loadApp()}
async function loadApp(){const r=await api('getApp',{token});if(!r.ok){localStorage.removeItem('finance_token');token=null;showLogin();return}appData=r;$('login').classList.add('hidden');$('forgot').classList.add('hidden');$('app').classList.remove('hidden');render()}
function logout(){api('logout',{token});localStorage.removeItem('finance_token');token=null;location.reload()}
function render(){const s=appData.settings||{};$('companyTitle').textContent=s.companyName||'Finance App';$('companySsm').textContent=s.ssmNumber?'SSM: '+s.ssmNumber:'';$('companyName').value=s.companyName||'';$('ssmNumber').value=s.ssmNumber||'';$('recoveryEmail').value=s.recoveryEmail||'';const tx=appData.transactions||[];let income=0,expense=0;tx.forEach(t=>t.type==='Income'?income+=Number(t.amount):expense+=Number(t.amount));$('income').textContent=money(income);$('expenses').textContent=money(expense);$('profit').textContent=money(income-expense);$('txBody').innerHTML=tx.map(t=>`<tr><td>${t.date}</td><td>${t.type}</td><td>${esc(t.category)}</td><td>${esc(t.description)}</td><td>${money(t.amount)}</td><td>${t.receiptUrl?`<a href="${t.receiptUrl}" target="_blank">View</a>`:''}</td><td><button onclick="delTx('${t.id}')">Delete</button></td></tr>`).join('');$('reportBox').innerHTML=`<div class="reportCard"><h3>Profit & Loss</h3><p>Total Income: <b>${money(income)}</b></p><p>Total Expenses: <b>${money(expense)}</b></p><p>Net Profit: <b>${money(income-expense)}</b></p></div><div class="reportCard"><h3>Expense by Category</h3>${expenseByCategory(tx)}</div>`}
function money(n){return 'RM '+Number(n||0).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2})}
function expenseByCategory(tx){const o={};tx.filter(t=>t.type==='Expense').forEach(t=>o[t.category]=(o[t.category]||0)+Number(t.amount));return Object.entries(o).map(([k,v])=>`<p>${esc(k)}: <b>${money(v)}</b></p>`).join('')||'<p>Tiada expense.</p>'}
async function saveTx(){const f=$('receipt').files[0];let receipt=null;if(f){receipt={name:f.name,mimeType:f.type,data:await file64(f)}}const r=await api('saveTransaction',{token,date:$('date').value,type:$('type').value,category:$('category').value,description:$('description').value,amount:$('amount').value,account:$('account').value,receipt});if(!r.ok){alert(r.error);return}['category','description','amount','account'].forEach(x=>$(x).value='');$('receipt').value='';await loadApp()}
async function delTx(id){if(!confirm('Delete transaction ini?'))return;const r=await api('deleteTransaction',{token,id});if(!r.ok)alert(r.error);else await loadApp()}
async function forgot(){const r=await api('forgotPassword',{email:$('forgotEmail').value});$('forgotMsg').textContent=r.ok?r.message:r.error}
async function saveSettings(){const r=await api('saveSettings',{token,companyName:$('companyName').value,ssmNumber:$('ssmNumber').value,recoveryEmail:$('recoveryEmail').value});$('settingsMsg').textContent=r.ok?'Settings berjaya disimpan.':r.error;if(r.ok)await loadApp()}
async function changePassword(){const r=await api('changePassword',{token,currentPassword:$('currentPassword').value,newPassword:$('newPassword').value});$('settingsMsg').textContent=r.ok?'Password berjaya ditukar.':r.error;if(r.ok){$('currentPassword').value='';$('newPassword').value=''}}
function openSettings(){showPage('settings')}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function file64(f){return new Promise((res,rej)=>{const rd=new FileReader();rd.onload=()=>res(rd.result.split(',')[1]);rd.onerror=rej;rd.readAsDataURL(f)})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
$('date').value=new Date().toISOString().slice(0,10);if(token)loadApp()
